"""empty message

Revision ID: 627d7fe71402
Revises: 62444d7d8fb3
Create Date: 2024-05-11 20:22:22.945539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627d7fe71402'
down_revision: Union[str, None] = '62444d7d8fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codebases', sa.Column('sha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codebases', 'sha')
    # ### end Alembic commands ###
